### ISSUE TITLE
Create 00 Boiler plate

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/from-react-to-redux-es6#1]
You can take as starting point:

boiler React project

https://github.com/Lemoncode/react-by-sample-es6/tree/master/00%20Boilerplate

boiler from-react-to-redux-ts

https://github.com/Lemoncode/from-react-to-redux-ts/tree/master/00%20Boilerplate

**Comment by carlostxm** [comment]
Pull request submitted.
